### ISSUE TITLE
tests failing with v0.0.37

### ISSUE THREAD

**Issue by 0xCalibur** [wighawag/forge-deploy#4]
Trying to port my tests to 0.0.37 but it's failing with
```
[FAIL. Reason: No cheatcode access granted for: 0x666f7267652d6465706c6f790000000000000000, see `vm.allowCheatcodes()`]
```

Repo/branch https://github.com/Abracadabra-money/abracadabra-money-contracts/tree/mim-layerzero

All my working in v0.0.36. For now I made a LegacyBaseTest so it's using barebone FoundryScript but would like to keep my repo up to date as you release new versions.

<img width="1196" alt="image" src="https://github.com/wighawag/forge-deploy/assets/92554750/7e34174a-d486-424e-b672-1d8ab43c3643">

**Comment by wighawag** [comment]
oh, that's interesting

reading https://book.getfoundry.sh/cheatcodes/allow-cheatcodes

i think it is because now the deployer is not deployed normally but its deployed code is injected at address `0x666f7267652d6465706C6f790000000000000000` which represent "forge-deploy" in hex format

and because of that it does not inherit the  cheatcode access

I probably need to call `vm.allowCheatcodes(0x666f7267652d6465706C6f790000000000000000)`

**Comment by wighawag** [comment]
I pushed v0.1.0 that now call`vm.allowCheatcodes` 
Did not tested but now I ll push patch version to only update sol files, as before now, I had to rebuild the binary

let me know if the issue is still there

**Comment by 0xCalibur** [comment]
I'm confirming this is now working. closing the issue, thx
