### ISSUE TITLE
Changing deployment name doesn't result in a new deployment

### ISSUE THREAD

**Issue by 0xCalibur** [wighawag/forge-deploy#6]
If I do
```
deployer.deploy_ElevatedMinterBurner("Moonriver_ElevatedMinterBurner", IMintableBurnable(mim));
```

deploy and sync, it creates a `Moonriver_ElevatedMinterBurner` deployment file.

but if I do next:
```
deployer.deploy_ElevatedMinterBurner("Moonriver_ElevatedMinterBurner2", IMintableBurnable(mim));
```

it will not deploy a new one.
At first I thought it could be because the bytecode and constructor args are the same but then I tried with

```
deployer.deploy_ElevatedMinterBurner("Moonriver_ElevatedMinterBurner2", IMintableBurnable(address(0)));
```

and still no deployment?

**Comment by wighawag** [comment]
Ok, I screwed up with 0.1.0
the autoBroadcast was disabled byt default because I use etch to deploy the contract and none of the variable initializer are obviously called. see fix: https://github.com/wighawag/forge-deploy/commit/196c81a5aab30272332a2e9105b2b2c958296cc1

Should be good in 0.1.1

Thanks for reporting!
